seed: 42
model_dir: ../../models/roid
resume_checkpoint: false

train:
  fp16: true
  batch_size: 32
  num_epochs: 2000
  save_interval: 100

data:
  data_file_path: ./filelists/data.txt

model:
  n_mel: 80

  embedding:
    n_phoneme: 114
    n_accent: 19

  encoder:
    channels: 576
    n_heads: 6
    n_layers: 6
    kernel_size: 3
    dropout: 0.1

  variance_adopter:
    channels: 576
    n_layers: 3
    dropout: 0.1

  decoder:
    channels: 192
    kernel_size: 5
    num_flows: 12
    num_layers: 4
    n_sqz: 2
    dropout: 0.05

optimizer:
  lr: 1.0
  betas: [0.9, 0.98]
